CPU = atmega8
PRG = accel_sensor

COMMONSRCS  = ../common/main.c ../common/crc.c ../common/sensor-uart.c
COMMONSRCS += ../common/i2c.c ../common/sensor.c
SRCS = local.c version.c ad7991.c ds1374.c

include ../common/Makefile.common
