CPU = atmega8
PRG = mass_sensor

COMMONSRCS  = ../common/main.c ../common/crc.c ../common/sensor-uart.c 
COMMONSRCS += ../common/i2c.c ../common/sensor.c
SRCS = local.c version.c ad5252.c adc.c

include ../common/Makefile.common
